DUNGEON: "
OOOOOOLOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOOOOOOOO
OOOOOOlOOOOOO"
